name: iOS build

on:
  push:
    branches:
      - master
      - development
      
jobs:
 deploy_ios:
    name: Build iOS Runner
    runs-on: macOS-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.5'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign --no-tree-shake-icons